<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY VIET SOLUTION
 /* CACHE FILE: Generated: Wed, 28 Jul 2004 10:38:07 GMT
 /* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE
 /* WRITTEN TO THE DATABASE AUTOMATICALLY
 /* Modify date: September 03, 2009
 /*--------------------------------------------------*/

class skin_global {

	//===========================================================================
	// css_external
	//===========================================================================
	function addCSS($cssUrl = "") {
		$BWHTML .= <<<EOF
<link type="text/css" rel="stylesheet" href="{$cssUrl}.css" />

EOF;
		return $BWHTML;
	}
	function addJavaScriptFile($file = "") {
		global $bw;
		$BWHTML = "";
		$BWHTML .= <<<EOF
<script type="text/javascript" src='{$bw->vars['board_url']}/javascripts/{$file}.js'></script>

EOF;
		return $BWHTML;
	}

	function addJavaScript($script = "") {
		$BWHTML .= <<<EOF
<script language="javascript" type="text/javascript">
{$script}
</script>

EOF;
return $BWHTML;
	}

	function SelectOption($options = array()) {
		$BWHTML .= <<<EOF
<option value="{$options['value']}" {$options['selected']}>{$options['name']}</option>
EOF;
		return $BWHTML;
	}

	function Select($options = array()) {
		$BWHTML .= <<<EOF
<select name="{$options['name']}" id="{$options['name']}"{$options['properties']}>
<!--OPTION LIST-->
</select>
EOF;
		return $BWHTML;
	}

	function addDropDownScript($id = "") {
		$BWHTML .= <<<EOF



EOF;
		return $BWHTML;
	}

	function PermissionDenied($error = "") {

		$BWHTML .= <<<EOF
<div class="red">
		{$error}</div>
EOF;
		return $BWHTML;
	}

	function displayFatalError($message = "", $line = "", $file = "", $trace = "") {
		$BWHTML .= <<<EOF
<div class="red" align="left" style="padding: 20px">
Error: {$message}<br />
Line: {$line}<br />
File: {$file}<br />
Trace: <pre>{$trace}</pre><br />
</div>
EOF;
		return $BWHTML;
	}

	function global_main_title() {
		global $vsPrint;
		$BWHTML .= <<<EOF
		{$vsPrint->mainTitle}
EOF;
		return $BWHTML;
	}
	//===========================================================================
	// vs_global
	//===========================================================================
	function vs_global() {
		global $bw, $vsUser, $vsLang;
		$BWHTML = "";
		$BWHTML .= <<<EOF
		<if=" !$vsUser->obj->getId() ">
			{$this->SITE_MAIN_CONTENT}
		<else />
		<center>
			<a target="_blank" href="{$bw->vars ['board_url']}" class="buttom_back_cd" title="{$bw->vars ['global_websitename']}">Trở lại trang chủ</a>
			<a target="_blank" href="http://www.vietsol.net" style="right:0px;left:auto;padding-left:25px;" class="buttom_back_cd logo_cd" title="{$vsLang->getWords('global_vietsolution_full','Công ty TNHH Thương Mại Điện Tử Giải Pháp Việt')}">
				{$vsLang->getWordsGlobal('global_version', 'VS FRAMEWORK 4.0')}
			</a>
			<div id="vsf-wrapper-container">
			<div id="vsf-wrapper" align="center">
			<!-- BEGIN OF HEADER -->
			<div class="vsf-header">
				<div class="header_vs_ceedos">
						<span>Admin Control Panel</span>
				</div>
			    <div class="clear"></div>
				<!-- BEGIN OF TOP MENU -->
				<div class="vsf-topmenu" id="topmenu">
					<ul>
						<if=" $this->ADMIN_TOP_MENU ">
						<foreach="$this->ADMIN_TOP_MENU as $menu">
						<li ><a href="{$menu->getUrl(0)}" title="{$menu->getTitle()}" >{$menu->getTitle()}</a>
							<if="$menu->isDropdown&&count($menu->children)">
			                    <ul>
			                    <foreach="$menu->children as $obj">
			                    <li><a href="{$obj->getUrl(0)}" title="{$obj->getTitle()}">{$obj->getTitle()}</a></li>
			                    </foreach>
			                    </ul>
							</if>
						</li>
						</foreach>
						</if>
					</ul>
					<div class="clear"></div></div>
				<!-- END OF TOP MENU -->
			    <div class="clear"></div>
			</div>
			<!-- END OF HEADER -->
			
			<!-- BEGIN OF SITE NAV -->
			<div class="site-nav">
					{$vsLang->getWords('global_dungtaitrang', 'Bạn đang đứng tại trang')} :: {$vsLang->currentArrayWords['main_title']}
			    (<a href="javascript:vsf.get('{$bw->input['vs']}/','maincontent');">{$vsLang->getWords('global_refresh','Refresh')}</a>)
			    <div class="vsf-language-selection">
			    {$this->LANGUAGE_LIST}
			    </div>
			</div>
			<div class="clear"></div>
			<!-- END OF SITE NAV -->
			    {$this->ACP_HELP_SYSTEM}
			<!-- BEGIN OF MAIN PAGE CONTENT -->
			<div id="maincontent">
			    {$this->SITE_MAIN_CONTENT}
			<div class="clear"></div>
			</div>
			<!-- END OF MAIN PAGE CONTENT -->
			<div class="clear"></div>
			<!-- BEGIN OF FOOTER -->
			<div id="footer">
			    <img src="{$bw->vars['img_url']}/vsfooter-leftimg.jpg" style="float:left;" height="25" width="25" alt="vs" />
			    <span>
			    	<a href="http://www.vietsol.net" title="{$vsLang->getWords('global_vietsolution_full','Công ty TNHH Thương Mại Điện Tử Giải Pháp Việt')}" style="color:#000;">
			    		{$vsLang->getWordsGlobal('global_copyrights', 'Copyright VS Framework 4.0 by Viet Solution Commerce')}
			    	</a>
			    </span>
			    <img src="{$bw->vars['img_url']}/vsfooter-rightimg.jpg" style="float:right;" height="25" width="245" alt="vs" />
			</div>
			<!-- END OF FOOTER -->
			</div>
			</div>
		</center>
		</if>
EOF;
  		return $BWHTML;
	}
	
	function importantAjaxCallBack($Text="",$Url="",$css="") {
		global $bw;
		$BWHTML = "";
		//--starthtml--//
		//
		$BWHTML .= <<<EOF
<script type="text/javascript">
	$(document).ready(function(){
		Custom.init();
	});
</script>
EOF;

		//--endhtml--//
		return $BWHTML;
	}

	//===========================================================================
	// pop_up_window
	//===========================================================================

	//===========================================================================
	// Redirect
	//===========================================================================
	function Redirect($Text="",$Url="",$css="") {
		global $bw;
		$BWHTML = "";
		//--starthtml--//
		//
		$BWHTML .= <<<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/html40/loose.dtd">
<html>
	<head>
	<title>Redirecting...</title>
	<meta http-equiv='refresh' content='2; url=$Url' />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	$css
	<style type="text/css">
		.title
		{
			color:red;
		}
		.text
		{
			padding:10px;
			color:#009F3C;
		}
	</style>
	</head>
  	<body >
		<center>
		<table style="background-color:#6ac3cb" cellpadding="0" cellspacing="0" width="100%" height="100%"> 
			<tr>
				<td width="416px" align="center" valign="middle" style="background:url({$bw->vars ['board_url']}/styles/redirect/direct.jpg) no-repeat center  top;" height="432px">
						<br/><br/><br/><br/>
					<img src="{$bw->vars ['board_url']}/styles/redirect/turtle.gif">
					<br/><br/>
					<p class="text">{$Text}</p>
				    <a href='$Url' title="{$Url}" class="title">( Click here if you do not wish to wait )</a>
				 </td>
			</tr>  
		</table> 
		</center>
	</body>
</html>
EOF;

	//--endhtml--//
	return $BWHTML;
	}

	//**********************************************************************************************************************
	// Added by Vu
	//**********************************************************************************************************************


	function buildRadioButtonHTML($name = "", $checkedYes = true, $checkedNo = false, $readonly = "", $disabled = "", $sAttr = "") {
		$BWHTML = <<<EOF
<input type="radio" name="{$name}" value="Yes" $checkedYes $readonly $disabled $sAttr style='width:10px; margin-right:10px;'>Yes</input>
<input type="radio"  name="{$name}" value="No" $checkedNo $readonly $disabled $sAttr style='width:10px; margin-right:10px;'>No</input>
EOF;
		return $BWHTML;
	}

	function buildTextTypeHTML($textType, $id, $name, $value, $readonly, $disabled, $sAttr) {
		$BWHTML = <<<EOF
<input type="$textType" id="{$id}" name="{$name}" value="$value" {$readonly} {$disabled} {$sAttr}></input>
EOF;
		return $BWHTML;
	}

	function buildCheckBoxHTML($id, $name, $checked, $readonly, $disabled, $sAttr) {
		$BWHTML = <<<EOF
<input type="checkbox" id="{$id}" name="{$name}" value="1" $readonly $checked $disabled $sAttr></input>
EOF;
		return $BWHTML;
	}

	function buildDropdownBoxHTML($id, $name, $currentValue, $currentDisplay, $listOption) {
		$BWHTML = <<<EOF
<select id="{$id}" name="{$name}">
<option value="{$currentValue}">{$currentDisplay}</option>
		{$listOption}
</select>
EOF;
		return $BWHTML;
	}

	function buildOptionHTML($value, $display, $sAtr) {
		$BWHTML = <<<EOF
<option value="{$value}" $sAtr>{$display}</option>
EOF;
		return $BWHTML;
	}

	function buildRadioButtonHTML1($sAttr = "") {
		$BWHTML = <<<EOF
<input type="radio" {$sAttr}>Yes</input>
<input type="radio" {$sAttr}>No</input>
EOF;
		return $BWHTML;
	}

	function buildTextTypeHTML1($sAttr) {
		$BWHTML = <<<EOF
<input {$sAttr}></input>
EOF;
		return $BWHTML;
	}

	function buildCheckBoxHTML1($sAttr) {
		$BWHTML = <<<EOF
<input type="checkbox" {$sAttr}></input>
EOF;
		return $BWHTML;
	}
}

?>